# Generated by Django 3.2.20 on 2023-09-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0002_rename_approver_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
