# Generated by Django 3.2.20 on 2023-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0003_auto_20230907_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
