# Generated by Django 3.2.20 on 2023-11-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ink', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='ink.Profile'),
        ),
    ]
